= Android Testing Training

25 January 2016

*Marius Mailat*, +<marius.mailat@gmail.com>+
http://thewnewcircle.com[The New Circle, Inc.]

== Obtaining Course Materials

You can either clone this Git repository:

  git clone git://github.com/mailat/android-testing-2016-01-25.git

or

   download a Zip archive by clicking the link at the top of the page or using the link: https://github.com/mailat/android-testing-2016-01-25/archive/master.zip

== Useful Links

Git book: http://git-scm.com/book

Marakana Java Fundamentals Tutorial: http://marakana.com/bookshelf/java_fundamentals_tutorial/index.html

Introduction to Eclipse - Driving Java Productivity: http://mrkn.co/s/video_introduction_to_eclipse_driving_java_productivity,595/index.html

Java Tutorial http://docs.oracle.com/javase/tutorial/

Gradle NDK Experimental plugin transition - http://tools.android.com/tech-docs/new-build-system/gradle-experimental

Gradle NDK Experimental plugin - http://de.slideshare.net/ph0b/mastering-the-ndk-with-android-studio-and-the-gradleexperimental-plugin

Marius presentation on how to secure an Android app + decompiling - http://de.slideshare.net/fastlink2/20140917-curious-mindshowsecureareyourlocalapps

== What should you start after finishing the training?

- Android Dev Summit coding labs 2015 - https://www.code-labs.io/android-dev-summit

== Homework Day 01

- If you already finished the Android Bootcamp: do the first 1-6 setps in https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Fandroid-dev-summit&viewga=UA-69243313-1#0
- If you did not attend the Android Bootcamp: Display a Toast when a message is posted to the yamba server. In the Post activity, if you have entered between 20-10 chars change the counter colour to yellow.

== Homework Day 02

- If you already finished the Android Bootcamp: finish the last steps in the session lab in https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Fandroid-dev-summit&viewga=UA-69243313-1#0
- If you did not attend the Android Bootcamp: Create a Broadcast receiver which detects if the internet is returned after a FLIGHT MODE ON for example and refresh the Timeline events


== Homework Day 03

- If you did not attend the Android Bootcamp: Please follow the coding lab - https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Fandroid-dev-summit&viewga=UA-69243313-1#0
- for all finish the "Push Your Code to Gitlab" chapter

